export const ERR_UPDATE = "ERR_UPDATE";
export const ERR_MISSING_INPUT = "ERR_MISSING_INPUT";
export const ERR_USER_NOT_FOUND = "ERR_USER_NOT_FOUND";
export const ERR_CREATE_SCHEDULE = "ERR_CREATE_SCHEDULE";