export const ERR_MISSING_INPUT = "ERR_MISSING_INPUT";
export const ERR_CREATE_CLASS = "ERR_CREATE_CLASS";
export const CLASS_IS_ALREADY_EXIST = "CLASS_IS_ALREADY_EXIST";
export const NO_PERMISSION = "NO_PERMISSION";
export const CLASS_NOT_FOUND = "CLASS_NOT_FOUND";