export const ERR_MISSING_INPUT = "ERR_MISSING_INPUT";
export const ERR_CREATE_CLASS = "ERR_CREATE_CLASS";
export const CLASS_IS_ALREADY_EXIST = "CLASS_IS_ALREADY_EXIST";
export const ERR_UPDATE_CLASS = "ERR_UPDATE_CLASS";
export const ERR_DELETE_CLASS = "ERR_DELETE_CLASS";
export const NO_PERMISSION = "NO_PERMISSION";